import puppeteer from 'puppeteer';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {mkdirSync} from 'node:fs';
const out=resolve('test/harness/shots-tv-guide');mkdirSync(out,{recursive:true});
const browser=await puppeteer.launch({headless:true,args:['--no-sandbox','--allow-file-access-from-files'],...(process.env.PUPPETEER_EXECUTABLE_PATH?{executablePath:process.env.PUPPETEER_EXECUTABLE_PATH}:{})});
const errors=[];const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));
await page.setViewport({width:1280,height:1100});await page.goto(pathToFileURL(resolve('test/harness/guide.html')).href);
await page.waitForFunction(()=>window.cards?.[1].shadowRoot?.querySelectorAll('.channel-list .channel').length===3);
const result=await page.evaluate(async()=>{
 const [compact,full]=cards;const root=full.shadowRoot;
 const labels=[...root.querySelectorAll('button')].every(b=>!!(b.getAttribute('aria-label')||b.textContent.trim()));
 const search=root.querySelector('input[type=search]');search.value='radio clasica';search.dispatchEvent(new Event('input'));await full.updateComplete;
 const found=root.querySelectorAll('.channel-list .channel').length;
 search.value='';search.dispatchEvent(new Event('input'));await full.updateComplete;
 root.querySelector('.star').click();await new Promise(r=>setTimeout(r,100));
 const shared=compact.shadowRoot.querySelectorAll('.favorites button').length===1;
 root.querySelector('.station').click();await full.updateComplete;
 const tune=calls.some(c=>c.service==='tune_channel'&&c.data.channel_key==='la1');
 const observed=compact.shadowRoot.querySelector('select').value==='boing';
 root.querySelector('button[aria-label^="Información"]').click();await full.updateComplete;await Promise.resolve();
 const modal=root.querySelector('dialog').open;
 return {labels,found,shared,tune,observed,modal};
});
assert.deepEqual(result,{labels:true,found:1,shared:true,tune:true,observed:true,modal:true});
await page.keyboard.press('Escape');await page.waitForFunction(()=>!cards[1].shadowRoot.querySelector('dialog').open);
await page.evaluate(()=>{cards[1].mode='guide';});await page.waitForFunction(()=>cards[1].shadowRoot.querySelector('.timeline'));
await page.screenshot({path:resolve(out,'guide-desktop.png'),fullPage:true});
await page.setViewport({width:393,height:850,deviceScaleFactor:2,isMobile:true,hasTouch:true});await page.waitForFunction(()=>window.cards?.[1].channels?.length===3);await page.evaluate(()=>{cards[1].mode='guide';});await page.waitForFunction(()=>cards[1].shadowRoot.querySelector('.timeline'));await page.screenshot({path:resolve(out,'guide-mobile.png'),fullPage:true});
assert(await page.evaluate(()=>getComputedStyle(cards[1].shadowRoot.querySelector('.timeline')).display==='none'&&getComputedStyle(cards[1].shadowRoot.querySelector('.mobile-guide')).display==='block'));
await page.evaluate(()=>{document.body.classList.add('dark');offline=true;refresh();});
await page.waitForFunction(()=>cards.every(c=>c.shadowRoot.querySelector('[role=alert]')));
const failures=await page.evaluate(()=>wsCount);await new Promise(r=>setTimeout(r,200));assert.equal(await page.evaluate(()=>wsCount),failures,'failed loads must not form a retry loop');
await page.screenshot({path:resolve(out,'guide-dark-offline.png'),fullPage:true});
await page.evaluate(()=>{offline=false;cards.forEach(c=>c.shadowRoot.querySelector('[role=alert] button').click());});
await page.waitForFunction(()=>cards.every(c=>!c.shadowRoot.querySelector('[role=alert]')));
assert.deepEqual(errors,[]);console.log('Guide: search, shared favorites, observed selection, dialog + Escape, responsive layout, failure recovery and labelled controls passed.');
await browser.close();
